### ISSUE TITLE
请问一下，是怎么打开小程序的，是要用visual studio吗

### ISSUE THREAD

**Issue by ai-qin** [EJianZQ/IGoLibrary#10]
小程序是需要在visualstudio里面下载.net插件，再打开吗

**Comment by EJianZQ** [comment]
你说的是什么小程序？是指程序的源代码吗？
如果你说的是运行程序的话，是不需要的，下载后按照教程使用即可

**Comment by ai-qin** [comment]
下载只能下载文件呀，那怎么运行程序呢，下载的文件里面并没有.exe文件呀，是打开那个：我去图书馆.sln文件吗

**Comment by ai-qin** [comment]
噢噢 不好意思不好意思，我刚刚没有下载软件，下载的是源文件，现在知道啦，谢谢你的回复！！！

**Comment by EJianZQ** [comment]
好的，没关系:)

**Comment by ai-qin** [comment]
你好，我再问一下，那个cookie有效时长大概是多久呀

**Comment by EJianZQ** [comment]
> 你好，我再问一下，那个cookie有效时长大概是多久呀

2个小时左右

**Comment by ai-qin** [comment]
好勒 谢谢！！
