### ISSUE TITLE
获取Cookies成功，但点击绑定后，Cookies验证失败

### ISSUE THREAD

**Issue by Xiao177** [EJianZQ/IGoLibrary#13]
hi, I want to use it for learning just now.
However, after I scan the QR code, share it's link to the software, and fill “获取Cookies”,then go to "绑定图书馆",
<img width="323" alt="image" src="https://github.com/EJianZQ/IGoLibrary/assets/116617166/dd2a8d8c-dc87-4d77-a12f-e48759c588ba">
click "绑定“，an error happened.
<img width="263" alt="image" src="https://github.com/EJianZQ/IGoLibrary/assets/116617166/b22df1c3-1c68-4bf7-a524-571b013f2a8c">
Unfortunately, I can't use it.
Can you help me.
thank u very much. @EJianZQ

**Comment by Xiao177** [comment]
Sorry, I know what's wrong. Skip this please.🤣

**Comment by EJianZQ** [comment]
哈哈，你很幽默。解决了就好

**Comment by cmj799** [comment]
我也遇到了这个问题，请问是怎么解决的呢？？

**Comment by cmj799** [comment]
获取Cookie成功 但是没有Authorization文件
![Uploading image.png…]()

**Comment by Xiao177** [comment]
> 我也遇到了这个问题，请问是怎么解决的呢？？

未来1个月特别忙，很抱歉不能及时帮你解决这个问题。当时是因为图书馆未开放才这样的。由于使用自建选座系统，后面也未使用这个选座了。待有空回头再看看。

**Comment by cmj799** [comment]
我自己尝试了另外获取cookie，能够在软件内正常使用（指获取自习室信息），我估计是这个获取cookie功能出了点问题
