### ISSUE TITLE
你好博主，要运行所有文件才可以有那个APP界面吗

### ISSUE THREAD

**Issue by Apageoflove** [EJianZQ/IGoLibrary#14]
我下载了那个desktop rutime 不知道怎么运行，我是大学生，这方面知识不太了解，也是刚姐出github不久，希望可以字典一二，在此不胜感谢

**Comment by EJianZQ** [comment]
https://github.com/EJianZQ/IGoLibrary/releases/tag/Public1.3
下载x64或x86的压缩包，然后解压
运行IGoLibrary-Winform.exe 即可
<img width="569" alt="微信图片_20231205151626" src="https://github.com/EJianZQ/IGoLibrary/assets/52780714/47a089ff-8ca0-44a1-90ab-80f77bdcbca1">
