### ISSUE TITLE
redirect_url与后台配置不一致

### ISSUE THREAD

**Issue by whatfka** [EJianZQ/IGoLibrary#17]
扫码获取cookie时候弹出这个错误，错误码10039。无法获取绑定信息的链接，可以修复一下吗

**Comment by cmj799** [comment]
这个我也遇到了，可以在网上找个可以替代的二维码来扫

**Comment by cmj799** [comment]
研究了二维码的内容发现是最近url从http改为https了，可以自己改一下

**Comment by stream-arch** [comment]
> 这个我也遇到了，可以在网上找个可以替代的二维码来扫

我找其他的替代扫了，但是复制完链接提交显示code链接格式有误解析不出cookies

**Comment by stream-arch** [comment]
但是在其他软件就可以解析出来

**Comment by cmj799** [comment]
应该是解析cookies的部分出错了，我抓包出来的cookies是可以直接填入用的

**Comment by EJianZQ** [comment]
已经提交了新的commit解决了这个问题
