### ISSUE TITLE
保存或收藏上次座位

### ISSUE THREAD

**Issue by Ryvict** [EJianZQ/IGoLibrary#2]
在我们学校的座位中，会出现间隔可座的设置。如果批量进行预约的话，会选中未开放的座位，导致循环中断，为了避免这种情况，只能ctrl一个一个选中加入，能否保存或收藏上次选中的座位？（收藏座位按钮一直无法使用）

**Comment by EJianZQ** [comment]
收藏的功能目前是没有做，因为最近忙，会抽时间做的，但是时间不能确定，还请谅解:)

**Comment by EJianZQ** [comment]
你好，由于我最近比较空闲，接下来1~2周内会上线收藏功能的，请期待

**Comment by EJianZQ** [comment]
我

**Comment by EJianZQ** [comment]
[增加抢座页面的收藏座位功能](https://github.com/EJianZQ/IGoLibrary/commit/19819843c7dc7e63305013d3f3389172c3a8ca44)
你好，已在这个Commit中实现
