### ISSUE TITLE
占座功能

### ISSUE THREAD

**Issue by Paralell-JT** [EJianZQ/IGoLibrary#4]
RT，由于我们学校取消预约后有五分钟的冷却，但是客户端是一分钟之后就开始循环预约，所以冲突报错。请问，以后可以加入更改循环预约时间的选项么？By the way，Cookie保活功能什么时候可以上线嘞，辛苦了，大佬。

**Comment by EJianZQ** [comment]
你好，我了解到了占座冷却的问题，因为我的学校是1分钟，所以我就只做了1分钟，没有考虑到这个问题。我将会在接下来一周内修复这个问题。
BTW，Cookie保活由于技术问题，一直在无限期拖延中，sad

**Comment by EJianZQ** [comment]
[占座功能中取消后重新预约的冷却时间可手动设置](https://github.com/EJianZQ/IGoLibrary/commit/9d12f4fec2686319615309a88d7fe01a0b3c3748)
已在这个Commit中实现

**Comment by Paralell-JT** [comment]
Thanks~
