### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by iSnolc** [EJianZQ/IGoLibrary#8]
# 验证码问题
6:55开始抢，到7点图书馆开放，然后小程序就显示有验证码，遇到了错误，就这一会儿，就抢不到座位了。图书馆在每天早上刚开放的时候要验证码，验证码我觉得应该不能直接ocr，但是可以至少弹出窗口显示出来验证码和输入框。这样自己也能填写上快人一步

**Comment by EJianZQ** [comment]
由于我这里抢座的时候没有出现过要验证码，所以我就没有办法抓到验证码的接口，没有办法去研究它:(
