### ISSUE TITLE
能支持一下macos吗

### ISSUE THREAD

**Issue by x03upstream** [EJianZQ/IGoLibrary#9]
如题

**Comment by EJianZQ** [comment]
能，但是很遗憾的是我目前很难抽出时间来写多平台。
到明年我应该会重构这个项目，来支持跨平台。
我的核心功能部分是本来就实现跨平台的，只是界面部分是winform，因此如果有能力可以自己动手一下，或者等我来重构这个项目
十分抱歉:(
